# Generated by Django 4.2.1 on 2023-05-24 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_userinfo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRequest',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate_request', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score_percentage', models.PositiveSmallIntegerField(verbose_name='Процент выполнения теста')),
                ('status', models.CharField(choices=[('WAITING', 'Ожидает рассмотрения'), ('ACCEPTED', 'Принята'), ('DECLINED', 'Отклонена')], default='WAITING', max_length=16, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка кандидата',
                'verbose_name_plural': 'Заявки кандидатов',
            },
        ),
    ]
