version: "3.8"

services:
  database:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_name
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_name
      - db_user
      - db_password
    networks:
      - my_network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    networks:
      - my_network

  backend:
    image: deevgeny/task-16-backend:deploy
    restart: always
    volumes:
      - media:/app/media/
      - static:/app/static/
    environment:
      DB_ENGINE: $DB_ENGINE
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DEBUG: 0
      ADMIN_CREDENTIALS_FILE: /run/secrets/admin_credentials
      ALLOWED_HOSTS: $ALLOWED_HOSTS
      CSRF_TRUSTED_ORIGINS: $CSRF_TRUSTED_ORIGINS
      CORS_ALLOWED_ORIGINS: $CORS_ALLOWED_ORIGINS
    secrets:
      - db_name
      - db_user
      - db_password
      - secret_key
      - admin_credentials
    networks:
      - my_network
    depends_on:
      - database

  frontend:
    image: deevgeny/task-16-frontend:deploy
    networks:
      - my_network
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.https.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/certificates:/etc/letsencrypt
      - ./certbot/webroot:/var/www/certbot
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - frontend
    networks:
      - my_network
      - web
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/certificates:/etc/letsencrypt
      - ./certbot/webroot:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {your email} -d {your domain} --agree-tos

volumes:
  postgres_data:
  static:
  media:

secrets:
  db_name:
    environment: POSTGRES_DB
  db_user:
    environment: POSTGRES_USER
  db_password:
    environment: POSTGRES_PASSWORD
  secret_key:
    environment: SECRET_KEY
  admin_credentials:
    file: ./admin_credentials


networks:
  web:
    internal: false
  my_network:
    internal: true
