# Base image
FROM python:3.11-slim AS base

WORKDIR /app

# Install python packages
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir --disable-pip-version-check

# Copy sources
COPY . .

# Run image
FROM base AS run

WORKDIR /app

EXPOSE 8000

CMD ["gunicorn", "config.wsgi:application", "--bind", "0:8000" ]
