# Generated by Django 4.2.1 on 2023-06-08 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternIntro',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='intro', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('url', models.URLField(verbose_name='Ссылка для перехода на стороннюю платформу')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Прогресс карьерной школы')),
            ],
            options={
                'verbose_name': 'Карьерная школа',
                'verbose_name_plural': 'Карьерная школа',
            },
        ),
        migrations.CreateModel(
            name='InternsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('test', models.TextField()),
                ('status', models.CharField(choices=[('WAITING', 'Ожидает рассмотрения'), ('ACCEPTED', 'Одобрена'), ('DECLINED', 'Отклонена')], db_index=True, default='WAITING', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interns_requests', to='staff.organization', verbose_name='Организация')),
            ],
        ),
    ]
