# Generated by Django 4.2.1 on 2023-06-08 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternCase',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='case', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание кейс чемпионата')),
                ('solution', models.FileField(blank=True, null=True, upload_to='case_solutions/', verbose_name='Решение')),
                ('status', models.CharField(choices=[('PASS', 'Пройден'), ('FAIL', 'Не пройден'), ('WAITING', 'Ожидает прохождения')], default='WAITING', max_length=16, verbose_name='Результат чемпионата')),
            ],
            options={
                'verbose_name': 'Кейс чемпионат',
                'verbose_name_plural': 'Кейс чемпионаты',
            },
        ),
        migrations.CreateModel(
            name='InternsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('test', models.TextField()),
                ('status', models.CharField(choices=[('WAITING', 'Ожидает рассмотрения'), ('ACCEPTED', 'Одобрена'), ('DECLINED', 'Отклонена')], db_index=True, default='WAITING', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='interns_requests', to='staff.organization', verbose_name='Организация')),
            ],
        ),
    ]
