# Generated by Django 4.2.1 on 2023-05-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internsrequest',
            name='test',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
