# Generated by Django 4.2.1 on 2023-06-08 07:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_internshipstate_userinfo_job_experience'),
        ('interns', '0002_internsrequest_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternIntro',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='intro', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('url', models.URLField(verbose_name='Ссылка для перехода на стороннюю платформу')),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=100)], verbose_name='Прогресс карьерной школы')),
            ],
            options={
                'verbose_name': 'Карьерная школа',
            },
        ),
    ]
