# Generated by Django 4.2.1 on 2023-06-08 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail')),
                ('role', models.CharField(choices=[('CANDIDATE', 'Кандидат'), ('INTERN', 'Стажер'), ('CURATOR', 'Куратор'), ('STAFF', 'Кадровый специалист'), ('MENTOR', 'Наставник')], db_index=True, default='CANDIDATE', max_length=16, verbose_name='Роль')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Номер телефона')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='staff.organization', verbose_name='Организация')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='InternshipState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='state', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stage', models.CharField(choices=[('REQUEST', 'Заявка'), ('INTRO', 'Карьерная школа'), ('TEST', 'Тестирование'), ('CASE', 'Кейс чемпионат'), ('CHOICE', 'Выбор места стажировки'), ('WORK', 'Работа на месте стажировки')], default='REQUEST', max_length=16, verbose_name='Этап отбора')),
                ('request_status', models.CharField(default='', max_length=16, verbose_name='Заявка')),
                ('intro_status', models.CharField(default='', max_length=16, verbose_name='Карьерная школа')),
                ('test_status', models.CharField(default='', max_length=16, verbose_name='Тестирование')),
                ('case_status', models.CharField(default='', max_length=16, verbose_name='Кейс чемпионат')),
                ('choice_status', models.CharField(default='', max_length=16, verbose_name='Выбор места стажировки')),
                ('work_status', models.CharField(default='', max_length=16, verbose_name='Работа на месте стажировки')),
            ],
            options={
                'verbose_name': 'Отбор на стажировку',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birthdate', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=6, null=True, verbose_name='Пол')),
                ('city', models.CharField(blank=True, max_length=60, verbose_name='Город проживания')),
                ('district', models.CharField(blank=True, max_length=60, verbose_name='Район проживания')),
                ('education_institution', models.CharField(blank=True, max_length=60, verbose_name='Учебное заведение')),
                ('education_city', models.CharField(blank=True, max_length=60, verbose_name='Город обучения')),
                ('faculty', models.CharField(blank=True, max_length=60, verbose_name='Факультет')),
                ('speciality', models.CharField(blank=True, max_length=60, verbose_name='Специальность')),
                ('graduation_year', models.PositiveIntegerField(null=True, verbose_name='Год выпуска')),
                ('education_level', models.CharField(blank=True, max_length=60, verbose_name='Уровень образования')),
                ('has_job_experience', models.BooleanField(null=True, verbose_name='Имеется опыт работы')),
                ('has_volunteer_experience', models.BooleanField(null=True, verbose_name='Имеется опыт волонтерства')),
                ('job_experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('citizenship', models.CharField(blank=True, max_length=50, verbose_name='Гражданство')),
                ('photo_url', models.URLField(null=True, verbose_name='Прямая ссылка на фотографию')),
                ('vk_id', models.CharField(blank=True, max_length=60, verbose_name='VK id')),
                ('telegram_id', models.CharField(blank=True, max_length=60, verbose_name='Telegram id')),
            ],
            options={
                'verbose_name': 'Информация о пользователе',
            },
        ),
    ]
