# Generated by Django 4.2.1 on 2023-05-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(blank=True, max_length=60, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='district',
            field=models.CharField(blank=True, max_length=60, verbose_name='Район проживания'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='education_city',
            field=models.CharField(blank=True, max_length=60, verbose_name='Город обучения'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='education_institution',
            field=models.CharField(blank=True, max_length=60, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='education_level',
            field=models.CharField(blank=True, max_length=60, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='faculty',
            field=models.CharField(blank=True, max_length=60, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=6, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='graduation_year',
            field=models.PositiveIntegerField(null=True, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job_experience',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo_url',
            field=models.URLField(null=True, verbose_name='Прямая ссылка на фотографию'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='speciality',
            field=models.CharField(blank=True, max_length=60, verbose_name='Специальноть'),
        ),
    ]
