# Generated by Django 4.2.1 on 2023-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userinfo_job_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='job_experience',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
    ]
