# Generated by Django 4.2.1 on 2023-05-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_patronymic_user_phone_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.TextField(blank=True, verbose_name='Направления стажировки'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_experience',
            field=models.TextField(blank=True, verbose_name='Опыт'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='user',
            name='university_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='user',
            name='university_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
    ]
