# Generated by Django 4.2.1 on 2023-06-08 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userinfo_job_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipState',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='state', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stage', models.CharField(choices=[('REQUEST', 'Заявка'), ('INTRO', 'Карьерная школа'), ('TEST', 'Тестирование'), ('CASE', 'Кейс чемпионат'), ('CHOICE', 'Выбор места стажировки'), ('WORK', 'Работа на месте стажировки')], default='REQUEST', max_length=16, verbose_name='Этап отбора')),
                ('request_status', models.CharField(default='', max_length=16, verbose_name='Заявка')),
                ('intro_status', models.CharField(default='', max_length=16, verbose_name='Карьерная школа')),
                ('test_status', models.CharField(default='', max_length=16, verbose_name='Тестирование')),
                ('case_status', models.CharField(default='', max_length=16, verbose_name='Кейс чемпионат')),
                ('choice_status', models.CharField(default='', max_length=16, verbose_name='Выбор места стажировки')),
                ('work_status', models.CharField(default='', max_length=16, verbose_name='Работа на месте стажировки')),
            ],
            options={
                'verbose_name': 'Отбор на стажировку',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='job_experience',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
    ]
