# Generated by Django 4.2.1 on 2023-05-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_organization_userinfo_citizenship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
